name: A workflow for my Hello World file
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    name: Hello world action
    runs-on: self-hosted
    steps:
    - name: hello
      run: |
        echo 'hello' >> /opt/test.txt
